name: build

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/build.yml'
  push:
    branches: [trunk]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/build.yml'
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

env:
  ARTIFACT_NAME: ${{ inputs.artifact-name || format('tosbreaker-build-{0}', github.run_id) }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: check
        run: pnpm check && pnpm check-scripts && pnpm lint

      - name: build
        run: pnpm build

      - name: stage artifacts
        run: |
          mkdir -p out
          cp dist/*.inu.js out/
          node scripts/build-info.ts dist out/build-info.json

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: out/*
          if-no-files-found: error
          retention-days: ${{ inputs.artifact-name && 1 || 30 }}
